export const SET_USER_ORDERNO_ARRAY = 'SET_USER_ORDERNO_ARRAY'
export const SET_USER_SUBMIT_OUTTRADENO = 'SET_USER_SUBMIT_OUTTRADENO'
export const SET_MY_ORDER_INFORMATION = 'SET_MY_ORDER_INFORMATION'
export const CANCEL_MY_ORDER_INFORMATION = 'CANCEL_MY_ORDER_INFORMATION'
